# Generated by Django 2.2.1 on 2019-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190508_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
