# Generated by Django 2.2.1 on 2019-05-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190509_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
