# Generated by Django 2.2.1 on 2019-05-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190509_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likebwit',
            name='bwit',
        ),
        migrations.RemoveField(
            model_name='likebwit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bwit',
        ),
        migrations.DeleteModel(
            name='LikeBwit',
        ),
    ]
