# Generated by Django 2.2.1 on 2019-05-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_connection'),
        ('accounts', '0006_auto_20190513_0836'),
    ]

    operations = [
    ]
