# Generated by Django 2.2.1 on 2019-05-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20190513_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bwit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=20)),
                ('picture', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_bwits', to='accounts.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='LikeBwit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bwit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bwit_likes', to='bwits.Bwit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='accounts.CustomUser')),
            ],
        ),
    ]
