# Generated by Django 2.2.1 on 2019-05-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190513_0836'),
        ('bwits', '0002_auto_20190513_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likebwit',
            unique_together={('user', 'bwit')},
        ),
    ]
