# Generated by Django 2.2.1 on 2019-05-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwits', '0006_auto_20190513_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebwit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
