# Generated by Django 2.2.1 on 2019-05-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bwits', '0003_auto_20190513_0931'),
        ('accounts', '0007_merge_20190513_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=21)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to='accounts.CustomUser')),
                ('bwit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bwit_comment', to='bwits.Bwit')),
            ],
        ),
    ]
